-- Insert 15 sample blog articles with images for testing
-- Run this in your Supabase SQL Editor

INSERT INTO blog_posts (
  title,
  slug,
  excerpt,
  content,
  featured_image,
  category,
  tags,
  is_published,
  is_featured,
  author_name,
  seo_title,
  seo_description,
  views_count,
  published_at
) VALUES
(
  'Les 10 Erreurs à Éviter Lors du Permis de Conduire',
  'erreurs-eviter-permis-conduire',
  'Découvrez les erreurs les plus courantes qui font échouer les candidats au permis de conduire et comment les éviter.',
  '<h2>Introduction</h2><p>Le jour de l''examen du permis de conduire est stressant pour tout le monde. Voici les 10 erreurs les plus fréquentes à éviter absolument.</p><h3>1. Oublier de régler les rétroviseurs</h3><p>Avant de démarrer, prenez le temps de bien ajuster tous vos rétroviseurs. C''est un point de contrôle essentiel.</p><h3>2. Ne pas contrôler les angles morts</h3><p>L''examinateur vérifie systématiquement que vous tournez la tête pour contrôler vos angles morts.</p><h3>3. Vitesse inadaptée</h3><p>Rouler trop vite OU trop lentement peut vous coûter des points. Adaptez votre vitesse aux conditions.</p><h3>4. Mauvais positionnement</h3><p>Restez bien dans votre voie et positionnez-vous correctement aux intersections.</p><h3>5. Clignotants oubliés</h3><p>Signalez toujours vos intentions avec vos clignotants, même si la route semble déserte.</p>',
  'https://images.unsplash.com/photo-1449965408869-eaa3f722e40d?w=800&q=80',
  'Conseils',
  ARRAY['permis', 'examen', 'erreurs', 'conseils'],
  true,
  true,
  'Auto-École Premium',
  'Les 10 Erreurs à Éviter au Permis - Guide Complet',
  'Découvrez les erreurs fatales qui font échouer au permis de conduire et comment les éviter pour réussir du premier coup.',
  245,
  NOW() - INTERVAL '2 days'
),
(
  'Comment Maîtriser le Créneau en 5 Étapes Simples',
  'maitriser-creneau-5-etapes',
  'Le créneau est souvent la manœuvre la plus redoutée. Apprenez à le réussir à tous les coups avec notre méthode simple.',
  '<h2>La méthode infaillible du créneau</h2><p>Le créneau n''a plus de secrets pour nos moniteurs. Voici la technique qui fonctionne à tous les coups !</p><h3>Étape 1 : Le positionnement</h3><p>Placez-vous parallèlement au véhicule de devant, à environ 50cm de distance.</p><h3>Étape 2 : La marche arrière</h3><p>Reculez doucement en tournant le volant à fond vers la place.</p><h3>Étape 3 : Le redressement</h3><p>Quand votre voiture fait un angle de 45°, tournez le volant de l''autre côté.</p><h3>Étape 4 : La correction</h3><p>Ajustez votre position en avançant et reculant si nécessaire.</p><h3>Étape 5 : Le contrôle final</h3><p>Vérifiez que vous êtes bien parallèle au trottoir et à bonne distance.</p>',
  'https://images.unsplash.com/photo-1506521781263-d8422e82f27a?w=800&q=80',
  'Manœuvres',
  ARRAY['créneau', 'stationnement', 'manœuvres', 'tutoriel'],
  true,
  true,
  'Auto-École Premium',
  'Maîtriser le Créneau : Guide Complet en 5 Étapes',
  'Apprenez à réussir votre créneau à tous les coups avec notre méthode simple en 5 étapes. Conseils de moniteurs professionnels.',
  389,
  NOW() - INTERVAL '5 days'
),
(
  'Conduite de Nuit : Nos Conseils pour Rester en Sécurité',
  'conduite-nuit-conseils-securite',
  'La conduite de nuit présente des défis particuliers. Découvrez comment adapter votre conduite pour rester en sécurité.',
  '<h2>Les particularités de la conduite nocturne</h2><p>Conduire la nuit demande une attention particulière et des réflexes adaptés.</p><h3>Visibilité réduite</h3><p>Vos feux de route sont essentiels, mais pensez à repasser en feux de croisement quand vous croisez un autre véhicule.</p><h3>Fatigue accrue</h3><p>La fatigue s''installe plus vite la nuit. Faites des pauses régulières toutes les 2 heures.</p><h3>Éblouissement</h3><p>Si vous êtes ébloui, ralentissez et fixez le bord droit de la chaussée.</p><h3>Animaux sauvages</h3><p>Soyez particulièrement vigilant en zone rurale où les animaux peuvent traverser.</p><h3>Distance de sécurité</h3><p>Augmentez vos distances de sécurité car le temps de réaction est plus long.</p>',
  'https://images.unsplash.com/photo-1513829596324-4bb2800c5efb?w=800&q=80',
  'Sécurité',
  ARRAY['conduite nuit', 'sécurité', 'conseils', 'visibilité'],
  true,
  false,
  'Auto-École Premium',
  'Conduite de Nuit : Guide Complet pour Conducteurs',
  'Tous nos conseils pour conduire en toute sécurité la nuit. Techniques et astuces de moniteurs professionnels.',
  198,
  NOW() - INTERVAL '7 days'
),
(
  'Le Code de la Route : 10 Panneaux Souvent Confondus',
  'panneaux-signalisation-confondus',
  'Certains panneaux de signalisation se ressemblent beaucoup. Apprenez à les différencier pour ne plus faire d''erreur.',
  '<h2>Les panneaux qui portent à confusion</h2><p>Le code de la route comporte des centaines de panneaux. Voici ceux qui sont le plus souvent confondus.</p><h3>Stop vs Cédez le passage</h3><p>Le stop est octogonal et rouge, le cédez le passage est triangulaire inversé. Le stop impose un arrêt complet.</p><h3>Sens interdit vs Interdit de tourner</h3><p>Le sens interdit est un cercle rouge avec une barre blanche horizontale. L''interdiction de tourner montre une flèche barrée.</p><h3>Vitesse minimale vs maximale</h3><p>La vitesse minimale est sur fond BLEU, la maximale sur fond BLANC. Ne les confondez pas !</p><h3>Fin d''interdiction</h3><p>Un panneau barré signale la fin de l''interdiction ou de l''obligation qu''il représente.</p>',
  'https://images.unsplash.com/photo-1580099805076-c1bca2b0bbd2?w=800&q=80',
  'Code de la Route',
  ARRAY['panneaux', 'signalisation', 'code', 'apprentissage'],
  true,
  true,
  'Auto-École Premium',
  'Panneaux de Signalisation : Ne Les Confondez Plus !',
  'Guide complet des panneaux de signalisation souvent confondus. Apprenez à les différencier facilement.',
  412,
  NOW() - INTERVAL '10 days'
),
(
  'Éco-Conduite : Économisez du Carburant et Protégez l''Environnement',
  'eco-conduite-economiser-carburant',
  'L''éco-conduite permet de réduire votre consommation de carburant jusqu''à 20%. Découvrez toutes nos astuces.',
  '<h2>Qu''est-ce que l''éco-conduite ?</h2><p>L''éco-conduite est un ensemble de techniques qui permettent de réduire sa consommation de carburant et ses émissions de CO2.</p><h3>Anticipation</h3><p>Anticipez les ralentissements et les arrêts pour éviter les freinages brusques et les accélérations inutiles.</p><h3>Vitesse stable</h3><p>Maintenez une vitesse constante autant que possible. Utilisez le régulateur de vitesse sur autoroute.</p><h3>Rapports de vitesse</h3><p>Passez les rapports rapidement : vers 2000 tr/min pour le diesel, 2500 pour l''essence.</p><h3>Entretien du véhicule</h3><p>Un véhicule bien entretenu consomme moins. Vérifiez la pression des pneus régulièrement.</p><h3>Climatisation</h3><p>La climatisation augmente la consommation de 10 à 20%. Ne l''utilisez que quand c''est nécessaire.</p>',
  'https://images.unsplash.com/photo-1502877338535-766e1452684a?w=800&q=80',
  'Conseils',
  ARRAY['éco-conduite', 'économie', 'environnement', 'carburant'],
  true,
  true,
  'Auto-École Premium',
  'Éco-Conduite : Réduisez Votre Consommation de 20%',
  'Découvrez toutes les techniques d''éco-conduite pour économiser du carburant et réduire votre impact environnemental.',
  567,
  NOW() - INTERVAL '12 days'
),
(
  'Permis Boîte Automatique : Avantages et Inconvénients',
  'permis-boite-automatique-avantages',
  'Le permis BEA (boîte automatique) séduit de plus en plus. Est-ce le bon choix pour vous ?',
  '<h2>Le permis boîte automatique en détail</h2><p>Depuis 2017, il est possible de passer le permis uniquement sur boîte automatique. Voyons les pour et les contre.</p><h3>✅ Les avantages</h3><ul><li><strong>Apprentissage plus rapide</strong> : Sans embrayage, la coordination est plus simple</li><li><strong>Moins de stress</strong> : Idéal pour les personnes anxieuses</li><li><strong>Conduite en ville</strong> : Plus confortable dans les embouteillages</li><li><strong>Accessibilité</strong> : Parfait pour les personnes avec certains handicaps</li></ul><h3>❌ Les inconvénients</h3><ul><li><strong>Limitation</strong> : Vous ne pouvez conduire que des automatiques</li><li><strong>Parc automobile</strong> : Moins de véhicules disponibles à la location</li><li><strong>Coût</strong> : Les véhicules automatiques sont souvent plus chers</li></ul><h3>La formation passerelle</h3><p>Après 3 mois et 7h de formation, vous pouvez passer au permis classique.</p>',
  'https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?w=800&q=80',
  'Types de Permis',
  ARRAY['boîte automatique', 'permis BEA', 'formation', 'choix'],
  true,
  false,
  'Auto-École Premium',
  'Permis Boîte Automatique : Le Guide Complet 2024',
  'Tout savoir sur le permis BEA : avantages, inconvénients, coût et formation. Faites le bon choix pour votre permis.',
  334,
  NOW() - INTERVAL '15 days'
),
(
  'La Conduite sur Autoroute : Ce Qu''il Faut Savoir',
  'conduite-autoroute-guide-complet',
  'L''autoroute a ses propres règles. Maîtrisez-les pour conduire en toute sécurité à haute vitesse.',
  '<h2>Les spécificités de l''autoroute</h2><p>L''autoroute est l''infrastructure la plus sûre, mais elle demande une conduite adaptée.</p><h3>Insertion</h3><p>Sur la voie d''accélération, accélérez pour atteindre la vitesse du trafic. Vérifiez vos rétroviseurs et insérez-vous dans un créneau.</p><h3>Dépassement</h3><p>Signalez avec le clignotant, vérifiez l''angle mort, dépassez rapidement mais sans excès, puis rabattez-vous.</p><h3>Voie de gauche</h3><p>La voie de gauche est réservée au dépassement uniquement. Ne restez pas dessus.</p><h3>Distances de sécurité</h3><p>À 130 km/h, gardez au moins 73 mètres (2 traits blancs) avec le véhicule devant vous.</p><h3>Fatigue</h3><p>Faites une pause toutes les 2 heures. La monotonie de l''autoroute favorise l''endormissement.</p>',
  'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800&q=80',
  'Conduite',
  ARRAY['autoroute', 'sécurité', 'vitesse', 'dépassement'],
  true,
  false,
  'Auto-École Premium',
  'Conduite sur Autoroute : Le Guide du Conducteur',
  'Maîtrisez toutes les règles de conduite sur autoroute : insertion, dépassement, distances de sécurité et plus.',
  289,
  NOW() - INTERVAL '18 days'
),
(
  'Conduite par Temps de Pluie : Les Règles d''Or',
  'conduite-pluie-securite',
  'La pluie multiplie par deux le risque d''accident. Adaptez votre conduite avec nos conseils d''experts.',
  '<h2>Les dangers de la pluie</h2><p>La pluie réduit l''adhérence, la visibilité et augmente les distances de freinage. Voici comment adapter votre conduite.</p><h3>🌧️ Réduisez votre vitesse</h3><p>Sur route mouillée, réduisez votre vitesse de 20 km/h par rapport aux limites autorisées.</p><h3>👀 Visibilité</h3><p>Allumez vos feux de croisement, même en journée. Utilisez les feux de brouillard arrière uniquement si la visibilité est inférieure à 50m.</p><h3>⚠️ L''aquaplaning</h3><p>Si vos roues perdent l''adhérence :<ul><li>Ne freinez pas brusquement</li><li>Ne braquez pas</li><li>Levez doucement le pied de l''accélérateur</li><li>Tenez fermement le volant</li></ul></p><h3>🚗 Distance de sécurité</h3><p>Doublez vos distances de sécurité car le freinage est moins efficace.</p><h3>🔧 Entretien</h3><p>Vérifiez régulièrement vos pneus et vos essuie-glaces.</p>',
  'https://images.unsplash.com/photo-1527786356703-4b100091cd2c?w=800&q=80',
  'Sécurité',
  ARRAY['pluie', 'aquaplaning', 'sécurité', 'météo'],
  true,
  true,
  'Auto-École Premium',
  'Conduite sous la Pluie : Guide de Sécurité Complet',
  'Tous nos conseils pour conduire en sécurité sous la pluie : vitesse, visibilité, aquaplaning et prévention.',
  423,
  NOW() - INTERVAL '20 days'
),
(
  'Les Priorités aux Intersections : Ne Faites Plus d''Erreur',
  'priorites-intersections-regles',
  'Les règles de priorité sont essentielles pour éviter les accidents. Révisons ensemble tous les cas de figure.',
  '<h2>Comprendre les priorités</h2><p>Les intersections sont des points dangereux où 40% des accidents ont lieu. Maîtriser les priorités est vital.</p><h3>La règle de base : Priorité à droite</h3><p>En l''absence de signalisation, vous devez céder le passage aux véhicules venant de votre droite.</p><h3>Les panneaux prioritaires</h3><ul><li><strong>Stop</strong> : Arrêt obligatoire, cédez le passage à tous</li><li><strong>Cédez le passage</strong> : Ralentissez et cédez si nécessaire</li><li><strong>Route prioritaire</strong> : Vous avez la priorité</li></ul><h3>Ronds-points</h3><p>Au rond-point, priorité à ceux qui sont DÉJÀ sur l''anneau (sauf signalisation contraire).</p><h3>Cas particuliers</h3><p>Les véhicules d''urgence (gyrophares et sirène) ont toujours la priorité. Rangez-vous et laissez-les passer.</p>',
  'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800&q=80',
  'Code de la Route',
  ARRAY['priorités', 'intersections', 'règles', 'sécurité'],
  true,
  false,
  'Auto-École Premium',
  'Priorités aux Intersections : Le Guide Complet',
  'Maîtrisez toutes les règles de priorité aux intersections, ronds-points et cas particuliers. Ne faites plus d''erreur.',
  512,
  NOW() - INTERVAL '22 days'
),
(
  'Jeune Conducteur : Les 3 Années de Permis Probatoire',
  'permis-probatoire-jeune-conducteur',
  'Les 3 premières années après le permis sont cruciales. Découvrez toutes les règles du permis probatoire.',
  '<h2>Le permis probatoire expliqué</h2><p>Après l''obtention du permis, vous entrez en période probatoire avec un capital de 6 points (au lieu de 12).</p><h3>📅 Durée</h3><ul><li><strong>3 ans</strong> pour la formation traditionnelle</li><li><strong>2 ans</strong> si vous avez fait la conduite accompagnée</li></ul><h3>📈 Récupération des points</h3><p>Si aucune infraction n''est commise :<ul><li>+2 points après 1 an (→ 8 points)</li><li>+2 points après 2 ans (→ 10 points)</li><li>+2 points après 3 ans (→ 12 points)</li></ul></p><h3>🚗 Limitations de vitesse</h3><p>Vitesses réduites pour les jeunes conducteurs :<ul><li>110 km/h sur autoroute (au lieu de 130)</li><li>100 km/h sur voies rapides (au lieu de 110)</li><li>80 km/h sur routes (au lieu de 90)</li></ul></p><h3>⚠️ Disque "A"</h3><p>Obligatoire pendant toute la période probatoire. Amende de 35€ si absent.</p>',
  'https://images.unsplash.com/photo-1611831268231-1b2e2ab9fac0?w=800&q=80',
  'Réglementation',
  ARRAY['jeune conducteur', 'probatoire', 'points', 'réglementation'],
  true,
  false,
  'Auto-École Premium',
  'Permis Probatoire : Guide du Jeune Conducteur 2024',
  'Tout savoir sur le permis probatoire : durée, points, limitations de vitesse et obligations. Guide complet 2024.',
  678,
  NOW() - INTERVAL '25 days'
),
(
  'Le Stationnement : Règles et Astuces Pratiques',
  'stationnement-regles-astuces',
  'Du stationnement en créneau au parking souterrain, maîtrisez toutes les techniques de stationnement.',
  '<h2>Tout savoir sur le stationnement</h2><p>Le stationnement est une compétence essentielle qui demande de la pratique et de la technique.</p><h3>🅿️ Types de stationnement</h3><p><strong>En créneau</strong> : Le plus difficile, nécessite précision et technique.<br><strong>En épi</strong> : Plus simple, marche avant ou arrière.<br><strong>En bataille</strong> : Le plus courant, perpendiculaire à la voie.</p><h3>📏 Distances légales</h3><ul><li>Arrêt et stationnement interdits à moins de 5m d''un passage piéton</li><li>À moins de 5m avant un carrefour</li><li>Sur un passage piéton ou une piste cyclable</li><li>Devant une sortie de véhicules</li></ul><h3>💡 Astuces de pro</h3><p><strong>Rétroviseurs</strong> : Vos meilleurs alliés pour juger les distances.<br><strong>Angle de 45°</strong> : La clé pour un créneau réussi.<br><strong>Correction</strong> : N''hésitez pas à manœuvrer plusieurs fois.</p><h3>🚫 Stationnement gênant vs dangereux</h3><p><strong>Gênant</strong> : Amende de 35€.<br><strong>Dangereux</strong> : Amende de 135€ + retrait de 3 points + mise en fourrière possible.</p>',
  'https://images.unsplash.com/photo-1590362891991-f776e747a588?w=800&q=80',
  'Manœuvres',
  ARRAY['stationnement', 'créneau', 'parking', 'réglementation'],
  true,
  false,
  'Auto-École Premium',
  'Guide Complet du Stationnement : Règles et Techniques',
  'Maîtrisez toutes les techniques de stationnement et connaissez les règles à respecter. Conseils de moniteurs pros.',
  445,
  NOW() - INTERVAL '28 days'
),
(
  'L''Alcool au Volant : Conséquences et Sanctions',
  'alcool-volant-consequences-sanctions',
  'L''alcool est responsable de 30% des accidents mortels. Connaissez les risques et les sanctions.',
  '<h2>L''alcool et la conduite : le danger mortel</h2><p>L''alcool est la première cause d''accidents mortels en France. Il altère les réflexes, la vision et le jugement.</p><h3>📊 Taux d''alcoolémie</h3><ul><li><strong>0,2 g/L</strong> : Limite pour les jeunes conducteurs et période probatoire</li><li><strong>0,5 g/L</strong> : Limite pour tous les autres conducteurs</li><li><strong>0,8 g/L</strong> : Délit pénal avec sanctions très lourdes</li></ul><h3>⚖️ Sanctions entre 0,5 et 0,8 g/L</h3><ul><li>Amende forfaitaire : 135€</li><li>Retrait de 6 points</li><li>Suspension du permis jusqu''à 3 ans</li><li>Immobilisation du véhicule</li></ul><h3>⚖️ Sanctions au-delà de 0,8 g/L</h3><ul><li>Délit pénal</li><li>Jusqu''à 4500€ d''amende</li><li>Jusqu''à 2 ans de prison</li><li>Retrait de 6 points</li><li>Suspension ou annulation du permis</li><li>Stage de sensibilisation obligatoire</li></ul><h3>🚕 Alternatives</h3><p>Capitaine de soirée, taxi, transport en commun, hébergement sur place... Les solutions existent !</p>',
  'https://images.unsplash.com/photo-1569025690938-a00729c9e1f9?w=800&q=80',
  'Sécurité',
  ARRAY['alcool', 'sécurité', 'sanctions', 'prévention'],
  true,
  false,
  'Auto-École Premium',
  'Alcool au Volant : Risques, Sanctions et Prévention',
  'Tout savoir sur l''alcool au volant : taux légaux, sanctions, risques et alternatives. Prévention et responsabilité.',
  567,
  NOW() - INTERVAL '30 days'
),
(
  'La Conduite Accompagnée (AAC) : Le Meilleur Départ',
  'conduite-accompagnee-aac-avantages',
  'La conduite accompagnée augmente vos chances de réussite et réduit votre prime d''assurance. On vous explique tout.',
  '<h2>L''Apprentissage Anticipé de la Conduite</h2><p>La conduite accompagnée (AAC) permet d''apprendre dès 15 ans et d''acquérir une solide expérience.</p><h3>✅ Les avantages</h3><ul><li><strong>Taux de réussite</strong> : 75% vs 55% en formation classique</li><li><strong>Expérience</strong> : 3000 km minimum en conditions réelles</li><li><strong>Assurance</strong> : Surprime réduite de 50% la première année</li><li><strong>Permis probatoire</strong> : Seulement 2 ans au lieu de 3</li><li><strong>Confiance</strong> : Moins de stress le jour de l''examen</li></ul><h3>📋 Les conditions</h3><ul><li>Avoir 15 ans minimum</li><li>Accord parental</li><li>Accompagnateur avec permis depuis 5 ans minimum</li><li>Assurance du véhicule adaptée</li></ul><h3>📅 Le déroulement</h3><p><strong>Phase 1</strong> : Formation initiale (20h minimum)<br><strong>Phase 2</strong> : RDV préalable (2h avec accompagnateur)<br><strong>Phase 3</strong> : Conduite accompagnée (1 an min, 3000 km)<br><strong>Phase 4</strong> : 2 rendez-vous pédagogiques<br><strong>Phase 5</strong> : Passage du permis dès 17 ans</p><h3>💰 Le coût</h3><p>Environ 150€ de plus qu''une formation classique, mais économies sur l''assurance pendant plusieurs années.</p>',
  'https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=800&q=80',
  'Formation',
  ARRAY['conduite accompagnée', 'AAC', 'formation', 'apprentissage'],
  true,
  true,
  'Auto-École Premium',
  'Conduite Accompagnée : Le Guide Complet AAC 2024',
  'Tout savoir sur la conduite accompagnée (AAC) : avantages, conditions, déroulement et coût. Le meilleur départ !',
  789,
  NOW() - INTERVAL '33 days'
),
(
  'Le Contrôle Technique : Ce Qu''il Faut Savoir',
  'controle-technique-guide-complet',
  'Le contrôle technique est obligatoire tous les 2 ans. Découvrez comment bien le préparer et ce qui est vérifié.',
  '<h2>Tout sur le contrôle technique</h2><p>Le contrôle technique est une vérification obligatoire de l''état de votre véhicule, essentielle pour votre sécurité.</p><h3>📅 Quand faire le contrôle ?</h3><ul><li><strong>Premier contrôle</strong> : 4 ans après la première mise en circulation</li><li><strong>Contrôles suivants</strong> : Tous les 2 ans</li><li><strong>Véhicules +10 ans</strong> : Contrôle pollution renforcé</li></ul><h3>🔍 Les 133 points de contrôle</h3><p>Le contrôleur vérifie 133 points répartis en 10 fonctions :<ul><li>Freinage</li><li>Direction</li><li>Visibilité</li><li>Éclairage et signalisation</li><li>Liaisons au sol</li><li>Structure et carrosserie</li><li>Équipements</li><li>Organes mécaniques</li><li>Pollution et niveau sonore</li><li>Identification du véhicule</li></ul></p><h3>⚠️ Les anomalies</h3><p><strong>Mineure</strong> : Pas de contre-visite<br><strong>Majeure</strong> : Contre-visite dans les 2 mois<br><strong>Critique</strong> : Interdiction de circuler jusqu''à réparation</p><h3>💡 Bien préparer son contrôle</h3><ul><li>Vérifier les niveaux (huile, liquide de refroidissement)</li><li>Tester tous les feux</li><li>Contrôler les pneus et les essuie-glaces</li><li>Nettoyer le pare-brise et les rétroviseurs</li></ul>',
  'https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?w=800&q=80',
  'Entretien',
  ARRAY['contrôle technique', 'entretien', 'réglementation', 'véhicule'],
  true,
  false,
  'Auto-École Premium',
  'Contrôle Technique : Guide Complet et Préparation',
  'Tout savoir sur le contrôle technique automobile : fréquence, points vérifiés, préparation et sanctions.',
  356,
  NOW() - INTERVAL '35 days'
),
(
  'Téléphone au Volant : Dangers et Nouvelles Sanctions 2024',
  'telephone-volant-dangers-sanctions',
  'Utiliser son téléphone en conduisant multiplie par 23 le risque d''accident. Les sanctions se durcissent.',
  '<h2>Le fléau du téléphone au volant</h2><p>En 2024, l''usage du téléphone au volant est devenu la première cause d''inattention dans les accidents.</p><h3>📱 Ce qui est interdit</h3><ul><li>Tenir son téléphone en main</li><li>Téléphoner avec une oreillette ou un casque</li><li>Consulter ou envoyer des messages</li><li>Utiliser des applications</li><li>Regarder des vidéos</li></ul><h3>✅ Ce qui est autorisé</h3><ul><li>Kit mains-libres intégré au véhicule</li><li>Système Bluetooth du véhicule</li><li>Mais uniquement si stationné, pas à l''arrêt au feu rouge !</li></ul><h3>⚖️ Sanctions 2024</h3><ul><li><strong>Amende</strong> : 135€ (minorée à 90€, majorée à 375€)</li><li><strong>Points</strong> : Retrait de 3 points</li><li><strong>Si accident associé</strong> : Suspension de permis immédiate possible</li><li><strong>Récidive</strong> : Jusqu''à 750€ et suspension de 3 ans</li></ul><h3>📊 Les chiffres choquants</h3><ul><li>1 conducteur sur 3 utilise son téléphone en conduisant</li><li>Risque d''accident multiplié par 23</li><li>Temps de réaction augmenté de 50%</li><li>10% des accidents mortels impliquent le téléphone</li></ul><h3>💡 Solutions</h3><p>Mode "Ne pas déranger" en conduisant, mettre le téléphone dans la boîte à gants, applications de blocage automatique.</p>',
  'https://images.unsplash.com/photo-1556656793-08538906a9f8?w=800&q=80',
  'Sécurité',
  ARRAY['téléphone', 'inattention', 'sanctions', 'sécurité'],
  true,
  false,
  'Auto-École Premium',
  'Téléphone au Volant : Dangers et Sanctions 2024',
  'Tout savoir sur l''usage du téléphone au volant : ce qui est interdit, les sanctions 2024 et les dangers réels.',
  623,
  NOW() - INTERVAL '38 days'
);

-- Display success message
SELECT 
  '✅ 15 articles insérés avec succès !' as message,
  COUNT(*) as total_articles
FROM blog_posts;

